# Generated by Django 4.1.4 on 2022-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='malumot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
